# Generated by Django 5.1.2 on 2024-10-27 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newspaper_db',
            options={'managed': False},
        ),
    ]
