# Generated by Django 5.1.2 on 2024-10-28 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper_app', '0002_alter_newspaper_db_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='newspaper_db',
            table='newspaper_obj',
        ),
    ]
